export const lyricLanguages = [
  { code: 'de', name: 'Allemand' },
  { code: 'de-old', name: 'Allemand (ancien)' },
  { code: 'en', name: 'Anglais' },
  { code: 'en-old', name: 'Anglais (ancien)' },
  { code: 'arp', name: 'Arpitan (patois, franco-provençal)' },
  { code: 'bzh', name: 'Breton' },
  { code: 'bg', name: 'Bulgare' },
  { code: 'cat', name: 'Catalan' },
  { code: 'cor', name: 'Corse' },
  { code: 'hr', name: 'Croate'},
  { code: 'dk', name: 'Danois'},
  { code: 'es', name: 'Espagnol' },
  { code: 'fi', name: 'Finnois' },
  { code: 'fr', name: 'Français' },
  { code: 'fr-old', name: 'Français ancien' },
  { code: 'ga-old', name: 'Galaïco-portugais' },
  { code: 'cym', name: 'Gallois' },
  { code: 'ge', name: 'Géorgien' },
  { code: 'gr', name: 'Grec' },
  { code: 'hu', name: 'Hongrois' },
  { code: 'ie', name: 'Irlandais' },
  { code: 'it', name: 'Italien' },
  { code: 'la', name: 'Latin' },
  { code: 'lv', name: 'Lituanien' },
  { code: 'lt', name: 'Letton / Latgale' },
  { code: 'mk', name: 'Macédonien'},
  { code: 'no', name: 'Norvégien'},
  { code : 'oc', name: 'Occitan'},
  { code: 'pho', name: 'Phonétique (translittération fr.)' },
  { code: 'ru', name: 'Russe' },
  { code: 'scots', name: 'Scots (anglais écossais)' },
  { code: 'se', name: 'Suédois'},
  { code: 'sr', name: 'Serbe'},
  { code: 'ch', name: 'Suisse allemand' },
  { code: 'ua', name: 'Ukrainien' },
]

export const getLanguageName = (languageCode) => {
  if (!languageCode) return null
  return lyricLanguages.find(({ code }) => code === languageCode)?.name || languageCode
}
